name: Slack Notifications Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests (Example)
        run: |
          echo "Running tests..."
          sleep 3
          # exit 1  # Uncomment to simulate failure

      - name: Prepare Commit Message
        id: commit
        run: |
          COMMIT_MSG=$(jq -r '.head_commit.message // "No message"' "$GITHUB_EVENT_PATH" | tr '\n' ' ')
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            "*GitHub Action Notification*\n
            Job Name: ${{ github.job }}\n
            Git URL: https://github.com/${{ github.repository }}\n
            Git Branch: ${{ github.ref_name }}\n
            Commit ID: ${{ github.sha }}\n
            Git Commit Author: ${{ github.actor }}\n
            Git Commit Message: ${{ env.COMMIT_MSG }}\n
            STATUS: ${{ job.status }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
