name: Slack Notifications

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Notify Slack on Start
        if: always()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload-templated: "true"
          payload: |
            {
              "text": ":rocket: Workflow started",
              "attachments": [
                {
                  "fallback": "Workflow started - repo: ${{ github.repository }}, branch: ${{ github.ref_name }}",
                  "color": "#439FE0",
                  "fields": [
                    { "title": "Repository", "value": "${{ github.repository }}", "short": true },
                    { "title": "Branch", "value": "${{ github.ref_name }}", "short": true },
                    { "title": "Actor", "value": "${{ github.actor }}", "short": true },
                    { "title": "Commit", "value": "${{ env.SHORT_SHA }}", "short": true },
                    { "title": "Message", "value": "${{ github.event.head_commit.message }}" }
                  ]
                }
              ]
            }
